import type { InputData, GenerateOptions, GenerateResult, ParseSkipped, ParsedRow, BuiltEntity, PathSegment } from './types'
import { flatten } from './pipeline/flatten'
import { transform } from './pipeline/transform'
import { group } from './pipeline/group'
import { buildEntities } from './pipeline/build'
import { separate } from './pipeline/separate'
import { validateReferenceRows } from './pipeline/validate'
import { resolve } from './pipeline/resolve'
import { toRecord } from './store/toRecord'

/**
 * The library's sole entry point.
 *
 * Reason for returning GenerateResult instead of just Record:
 * Allows callers to inspect skipped entries without losing partial results
 */
export function generate(
  input: InputData,
  options?: GenerateOptions,
): GenerateResult {
  const { primary, reference, skipped } = parse(input, options)
  const entities = buildPrimary(primary)
  const refSkipped = processReference(reference, entities)
  return assembleResult(entities, skipped.concat(refSkipped))
}

/**
 * Reason for bundling flatten/transform/separate into one function:
 * Keeps generate() at a single abstraction level (Composed Method)
 */
function parse(
  input: InputData,
  options?: GenerateOptions,
): { readonly primary: readonly ParsedRow[]; readonly reference: readonly ParsedRow[]; readonly skipped: ParseSkipped[] } {
  // Reason for creating/destroying scoped cache in this function scope:
  // Module-level persistent cache risks unbounded growth of path strings
  const cache = new Map<string, readonly PathSegment[]>()
  const schema = options?.schema
  // Reason for defaulting here instead of in transform:
  // Ensures the spec is enforced at the generate level without depending on transform's internals
  const skipScope = options?.skipScope ?? 'cell'

  const flatRows = flatten(input)
  const { rows, skipped } = transform(flatRows, cache, schema, skipScope)
  const { primary, reference } = separate(rows)
  return { primary, reference, skipped }
}

/**
 * Reason for extracting as a separate function:
 * Symmetric with processReference, keeps generate() at a uniform abstraction level
 */
function buildPrimary(rows: readonly ParsedRow[]): BuiltEntity[] {
  const groups = group(rows)
  return buildEntities(groups)
}

/**
 * Reason for extracting as a separate function:
 * Keeps generate() free of output-formatting details (Composed Method)
 */
function assembleResult(
  entities: readonly BuiltEntity[],
  skipped: readonly ParseSkipped[],
): GenerateResult {
  const records = entities.map((e) => toRecord(e.store))
  return { result: collect(records), skipped: skipped.slice() }
}

/**
 * Process reference rows against existing entities.
 *
 * Reason for extracting as a separate function:
 * Aligns abstraction level with other pipeline stages called in generate()
 */
function processReference(
  reference: readonly ParsedRow[],
  entities: readonly BuiltEntity[],
): ParseSkipped[] {
  if (reference.length === 0) {
    return []
  }

  if (entities.length === 0) {
    // All rows are $key rows with no primary data → skip all reference rows
    return reference.map((row) => {
      const keyPair = row.pairs.find((p) => p.segments.some((s) => s.isKey))
      return {
        name: row.source.sheet,
        path: keyPair
          ? keyPair.segments.map((s) => s.isKey ? `$${s.name}` : s.name).join('.')
          : '',
        value: keyPair ? String(keyPair.value) : '',
        index: row.source.index,
        reason: 'no_primary_data' as const,
      }
    })
  }

  const { valid, skipped: vSkipped } = validateReferenceRows(reference)
  if (valid.length === 0) {
    return [...vSkipped]
  }

  const refGroups = group(valid)
  const { skipped: rSkipped } = resolve(refGroups, entities)
  return vSkipped.concat(rSkipped)
}

/**
 * Stage 5: Collect all records and aggregate values per top-level key into arrays.
 *
 * Bundles top-level entries from Records generated by each group under the same key,
 * storing values as arrays.
 *
 * Reason for using Map internally and converting only final output with Object.fromEntries:
 * Avoids dynamic property assignment (obj[key] = value) during the loop,
 * ensuring safe object construction (Map + Object.fromEntries avoids prototype pollution)
 */
function collect(records: readonly Record<string, unknown>[]): Record<string, unknown> {
  const result = new Map<string, unknown[]>()

  for (const record of records) {
    for (const [key, value] of Object.entries(record)) {
      const existing = result.get(key)
      if (existing !== undefined) {
        // Reason for using push: concat creates a new array each time,
        // while push only mutates the existing array, which is more memory-efficient.
        // result Map is a local variable used only within this function scope, so mutable operations are safe
        existing.push(value)
        continue
      }
      result.set(key, [value])
    }
  }

  return Object.fromEntries(result)
}
