import type { InputData, GenerateOptions, GenerateResult, PathSegment } from './types'
import { flatten } from './pipeline/flatten'
import { transform } from './pipeline/transform'
import { group } from './pipeline/group'
import { build } from './pipeline/build'

/**
 * The library's sole entry point.
 *
 * Connects the 5-stage pipeline to generate objects from input data.
 * flatten → transform → group → build → collect
 *
 * Reason for creating/destroying scoped cache (Map) in this function scope:
 * Module-level persistent cache risks unbounded growth of path strings
 *
 * Reason for returning GenerateResult instead of just Record:
 * Allows callers to inspect skipped entries without losing partial results
 */
export function generate(
  input: InputData,
  options?: GenerateOptions,
): GenerateResult {
  const cache = new Map<string, readonly PathSegment[]>()
  const schema = options?.schema
  // Reason for defaulting here instead of in transform:
  // Ensures the spec is enforced at the generate level without depending on transform's internals
  const skipScope = options?.skipScope ?? 'cell'

  const flatRows = flatten(input)
  const { rows: parsedRows, skipped } = transform(flatRows, cache, schema, skipScope)
  const groups = group(parsedRows)
  const records = build(groups)

  return { result: collect(records), skipped }
}

/**
 * Stage 5: Collect all records and aggregate values per top-level key into arrays.
 *
 * Bundles top-level entries from Records generated by each group under the same key,
 * storing values as arrays.
 *
 * Reason for using Map internally and converting only final output with Object.fromEntries:
 * Avoids dynamic property assignment (obj[key] = value) during the loop,
 * ensuring safe object construction (Map + Object.fromEntries avoids prototype pollution)
 */
function collect(records: readonly Record<string, unknown>[]): Record<string, unknown> {
  const result = new Map<string, unknown[]>()

  for (const record of records) {
    for (const [key, value] of Object.entries(record)) {
      const existing = result.get(key)
      if (existing !== undefined) {
        // Reason for using push: concat creates a new array each time,
        // while push only mutates the existing array, which is more memory-efficient.
        // result Map is a local variable used only within this function scope, so mutable operations are safe
        existing.push(value)
        continue
      }
      result.set(key, [value])
    }
  }

  return Object.fromEntries(result)
}
